### ISSUE TITLE
why does this exist

### ISSUE THREAD

**Issue by Sajo8** [athena-network/athena-block-monitor#2]

**Comment by Sajo8** [comment]
🤔

**Comment by brandonlehmann** [comment]
It looks like it monitors for new blocks...

**Comment by Sajo8** [comment]
doesnt, still set to turtlecoin daemon. 

are we going to change it around?

**Comment by brandonlehmann** [comment]
Looks like it's pointed at the right RPC port to me.

**Comment by Sajo8** [comment]
https://github.com/athena-network/athena-block-monitor/blob/master/bbot.py#L13

**Comment by Sajo8** [comment]
https://github.com/athena-network/ASBot/blob/master/asbot.py

**Comment by Sajo8** [comment]
we have rashed's thing anyways
